### ISSUE TITLE
Add code to read out response time from the box, not relying on system time.

### ISSUE THREAD

**Issue by guillermoaguilar** [wichmann-lab/psychopy-pixx#13]

**Comment by dekuenstle** [comment]
Thanks, @guillermoaguilar!  Do you have some code snippet/example/reference on how to to this?

**Comment by guillermoaguilar** [comment]
Yes, [our implementation in HRL](https://github.com/computational-psychology/hrl/blob/master/hrl/inputs/responsepixx.py) is an adapted copy of the example provided by the [official documentation by VPixx.](https://www.vpixx.com/manuals/python/html/basicdemo.html#example-8-how-to-read-button-presses-from-a-responsepixx
), here below:

``` python
from pypixxlib.datapixx import DATAPixx3
from psychopy import core

#connect to VPixx device
device = DATAPixx3()

#First, let's make a dictionary of codes that correspond to our buttons. This is in decimal.
#Note 1: these codes ARE NOT UNIVERSAL. You can check what your own button codes are using the PyPixx Digital I/O demo
#Note 2: these codes are for single button presses only. If two buttons are pressed at the same time this will generate a unique code, which we will ignore
buttonCodes = {65527:'blue', 65533:'yellow', 65534:'red', 65531:'green', 65519:'white', 65535:'button release'}
exitButton = 'white'

myLog = device.din.setDinLog(12e6, 1000)
device.din.startDinLog()
device.updateRegisterCache()
startTime = device.getTime()
finished = False


#let's create a loop which checks the schedule at 0.25 s intervals for button presses.
#Any time a button press is found, we print the timestamp and button pressed.
#If a designated exit button is pressed, we disconnect.
while finished == False:
    #read device status
    device.updateRegisterCache()
    device.din.getDinLogStatus(myLog)
    newEvents = myLog["newLogFrames"]

    if newEvents > 0:
        eventList = device.din.readDinLog(myLog, newEvents)

        for x in eventList:
           if x[1] in buttonCodes:
                #look up the name of the button
                buttonID = buttonCodes[x[1]]

                #get the time of the press, since we started logging
                time = round(x[0] - startTime, 2)
                printStr = 'Button pressed! Button code: ' + str(x[1]) + ', Button ID: ' + buttonID + ', Time:' + str(time)
                print(printStr)
                if buttonID == exitButton:
                    finished = True
    core.wait(0.25)

#Stop logging
device.din.stopDinLog()
device.updateRegisterCache()
```
The important lines are the `device.getTime()` which gets the time from the box and stores it, that is, the box's clock time at the start of the query, and then after a button is pressed, get from the Log data the time, which is stored as the first element (`x[0]`) in a list of events `x`.

I'll try to incorporate this in your code...

**Comment by dekuenstle** [comment]
Thanks! 
I probably misleadingly expressed myself in our conversation:
We already read the internal time-difference from the box (see [here](https://github.com/wichmann-lab/psychopy-pixx/blob/39f39799aee58a83347a71e4ac2492567d61cf96/psychopy_pixx/devices/responsepixx.py#L89) and  [here](https://github.com/wichmann-lab/psychopy-pixx/blob/39f39799aee58a83347a71e4ac2492567d61cf96/psychopy_pixx/devices/responsepixx.py#L110)), but we do not yet match this to the ViewPixx's frame onset time. 
I'm not sure if this is actually a problem, if you get the device time right after the frame flip, e.g., `window.flip; buttonbox.start()`.
